#![forbid(unsafe_code)]
//! Core contracts for mapper, service, wrapper, metadata, and SQL interception.

use futures::future::BoxFuture;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::BTreeMap;
use std::marker::PhantomData;
use std::sync::Arc;

/// Stable error type used by all rbatis-plus packages.
#[derive(Debug, thiserror::Error)]
pub enum PlusError {
    #[error("invalid argument: {0}")]
    InvalidArgument(String),
    #[error("mapper error: {0}")]
    Mapper(String),
    #[error("interceptor error at {stage:?}: {message}")]
    Interceptor {
        stage: InterceptorStage,
        message: String,
    },
}

pub type PlusResult<T> = Result<T, PlusError>;

/// Compile-time table metadata generated by `PlusModel`.
pub trait TableMetadata {
    const TABLE_NAME: &'static str;
    const COLUMNS: &'static [&'static str];
    const ID_COLUMN: &'static str;
    const VERSION_COLUMN: Option<&'static str> = None;
    const LOGIC_DELETE_COLUMN: Option<&'static str> = None;
}

/// A typed column reference without Java-style lambda reflection.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Column<T> {
    name: &'static str,
    marker: PhantomData<fn() -> T>,
}

impl<T> Column<T> {
    pub const fn new(name: &'static str) -> Self {
        Self {
            name,
            marker: PhantomData,
        }
    }

    pub const fn name(&self) -> &'static str {
        self.name
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Operator {
    Eq,
    Ne,
    Gt,
    Ge,
    Lt,
    Le,
    In,
    Like,
    IsNull,
    IsNotNull,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Predicate {
    pub column: String,
    pub operator: Operator,
    pub value: Value,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SortDirection {
    Asc,
    Desc,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Sort {
    pub column: String,
    pub direction: SortDirection,
}

/// Strongly typed query wrapper.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[must_use]
pub struct QueryWrapper<T> {
    predicates: Vec<Predicate>,
    sorts: Vec<Sort>,
    limit: Option<u64>,
    marker: PhantomData<fn() -> T>,
}

impl<T> Default for QueryWrapper<T> {
    fn default() -> Self {
        Self {
            predicates: Vec::new(),
            sorts: Vec::new(),
            limit: None,
            marker: PhantomData,
        }
    }
}

impl<T> QueryWrapper<T> {
    pub fn eq<V: Serialize>(mut self, column: &Column<T>, value: V) -> PlusResult<Self> {
        self.push_predicate(column, Operator::Eq, value)?;
        Ok(self)
    }

    pub fn ne<V: Serialize>(mut self, column: &Column<T>, value: V) -> PlusResult<Self> {
        self.push_predicate(column, Operator::Ne, value)?;
        Ok(self)
    }

    pub fn gt<V: Serialize>(mut self, column: &Column<T>, value: V) -> PlusResult<Self> {
        self.push_predicate(column, Operator::Gt, value)?;
        Ok(self)
    }

    pub fn ge<V: Serialize>(mut self, column: &Column<T>, value: V) -> PlusResult<Self> {
        self.push_predicate(column, Operator::Ge, value)?;
        Ok(self)
    }

    pub fn lt<V: Serialize>(mut self, column: &Column<T>, value: V) -> PlusResult<Self> {
        self.push_predicate(column, Operator::Lt, value)?;
        Ok(self)
    }

    pub fn le<V: Serialize>(mut self, column: &Column<T>, value: V) -> PlusResult<Self> {
        self.push_predicate(column, Operator::Le, value)?;
        Ok(self)
    }

    pub fn like<V: Serialize>(mut self, column: &Column<T>, value: V) -> PlusResult<Self> {
        self.push_predicate(column, Operator::Like, value)?;
        Ok(self)
    }

    pub fn r#in<V: Serialize>(mut self, column: &Column<T>, values: Vec<V>) -> PlusResult<Self> {
        self.push_predicate(column, Operator::In, values)?;
        Ok(self)
    }

    pub fn is_null(mut self, column: &Column<T>) -> Self {
        self.predicates.push(Predicate {
            column: column.name().to_owned(),
            operator: Operator::IsNull,
            value: Value::Null,
        });
        self
    }

    pub fn is_not_null(mut self, column: &Column<T>) -> Self {
        self.predicates.push(Predicate {
            column: column.name().to_owned(),
            operator: Operator::IsNotNull,
            value: Value::Null,
        });
        self
    }

    pub fn order_by(mut self, column: &Column<T>, direction: SortDirection) -> Self {
        self.sorts.push(Sort {
            column: column.name().to_owned(),
            direction,
        });
        self
    }

    pub const fn limit(mut self, limit: u64) -> Self {
        self.limit = Some(limit);
        self
    }
    pub fn predicates(&self) -> &[Predicate] {
        &self.predicates
    }
    pub fn sorts(&self) -> &[Sort] {
        &self.sorts
    }
    pub const fn row_limit(&self) -> Option<u64> {
        self.limit
    }

    fn push_predicate<V: Serialize>(
        &mut self,
        column: &Column<T>,
        operator: Operator,
        value: V,
    ) -> PlusResult<()> {
        self.predicates.push(Predicate {
            column: column.name().to_owned(),
            operator,
            value: serde_json::to_value(value)
                .map_err(|error| PlusError::InvalidArgument(error.to_string()))?,
        });
        Ok(())
    }
}

/// Typed update wrapper sharing query predicates.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[must_use]
pub struct UpdateWrapper<T> {
    pub query: QueryWrapper<T>,
    pub assignments: BTreeMap<String, Value>,
}

impl<T> Default for UpdateWrapper<T> {
    fn default() -> Self {
        Self {
            query: QueryWrapper::default(),
            assignments: BTreeMap::new(),
        }
    }
}

impl<T> UpdateWrapper<T> {
    pub fn set<V: Serialize>(mut self, column: &Column<T>, value: V) -> PlusResult<Self> {
        self.assignments.insert(
            column.name().to_owned(),
            serde_json::to_value(value)
                .map_err(|error| PlusError::InvalidArgument(error.to_string()))?,
        );
        Ok(self)
    }
    pub fn where_query(mut self, query: QueryWrapper<T>) -> Self {
        self.query = query;
        self
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PageRequest {
    pub current: u64,
    pub size: u64,
}

impl PageRequest {
    pub fn new(current: u64, size: u64) -> PlusResult<Self> {
        if current == 0 || size == 0 {
            return Err(PlusError::InvalidArgument(
                "page current and size must be greater than zero".into(),
            ));
        }
        Ok(Self { current, size })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Page<T> {
    pub records: Vec<T>,
    pub total: u64,
    pub current: u64,
    pub size: u64,
}

/// MyBatis-Plus compatible mapper surface.
pub trait BaseMapper<T, Id>: Send + Sync {
    fn insert(&self, entity: T) -> BoxFuture<'_, PlusResult<T>>;
    fn select_by_id(&self, id: Id) -> BoxFuture<'_, PlusResult<Option<T>>>;
    fn select_list(&self, query: QueryWrapper<T>) -> BoxFuture<'_, PlusResult<Vec<T>>>;
    fn select_page(
        &self,
        page: PageRequest,
        query: QueryWrapper<T>,
    ) -> BoxFuture<'_, PlusResult<Page<T>>>;
    fn update_by_id(&self, entity: T) -> BoxFuture<'_, PlusResult<T>>;
    fn update(&self, update: UpdateWrapper<T>) -> BoxFuture<'_, PlusResult<u64>>;
    fn delete_by_id(&self, id: Id) -> BoxFuture<'_, PlusResult<bool>>;
    fn insert_batch(&self, entities: Vec<T>) -> BoxFuture<'_, PlusResult<Vec<T>>>;
}

/// Service API delegating to a mapper.
pub trait IService<T, Id>: Send + Sync {
    fn save(&self, entity: T) -> BoxFuture<'_, PlusResult<T>>;
    fn get_by_id(&self, id: Id) -> BoxFuture<'_, PlusResult<Option<T>>>;
    fn list(&self, query: QueryWrapper<T>) -> BoxFuture<'_, PlusResult<Vec<T>>>;
    fn page(
        &self,
        request: PageRequest,
        query: QueryWrapper<T>,
    ) -> BoxFuture<'_, PlusResult<Page<T>>>;
    fn update_by_id(&self, entity: T) -> BoxFuture<'_, PlusResult<T>>;
    fn update(&self, update: UpdateWrapper<T>) -> BoxFuture<'_, PlusResult<u64>>;
    fn remove_by_id(&self, id: Id) -> BoxFuture<'_, PlusResult<bool>>;
    fn save_batch(&self, entities: Vec<T>) -> BoxFuture<'_, PlusResult<Vec<T>>>;
}

#[derive(Debug)]
pub struct ServiceImpl<M> {
    mapper: Arc<M>,
}
impl<M> ServiceImpl<M> {
    pub fn new(mapper: Arc<M>) -> Self {
        Self { mapper }
    }
    pub fn mapper(&self) -> &M {
        &self.mapper
    }
}

impl<T, Id, M> IService<T, Id> for ServiceImpl<M>
where
    T: Send + 'static,
    Id: Send + 'static,
    M: BaseMapper<T, Id> + 'static,
{
    fn save(&self, entity: T) -> BoxFuture<'_, PlusResult<T>> {
        self.mapper.insert(entity)
    }
    fn get_by_id(&self, id: Id) -> BoxFuture<'_, PlusResult<Option<T>>> {
        self.mapper.select_by_id(id)
    }
    fn list(&self, query: QueryWrapper<T>) -> BoxFuture<'_, PlusResult<Vec<T>>> {
        self.mapper.select_list(query)
    }
    fn page(
        &self,
        request: PageRequest,
        query: QueryWrapper<T>,
    ) -> BoxFuture<'_, PlusResult<Page<T>>> {
        self.mapper.select_page(request, query)
    }
    fn update_by_id(&self, entity: T) -> BoxFuture<'_, PlusResult<T>> {
        self.mapper.update_by_id(entity)
    }
    fn update(&self, update: UpdateWrapper<T>) -> BoxFuture<'_, PlusResult<u64>> {
        self.mapper.update(update)
    }
    fn remove_by_id(&self, id: Id) -> BoxFuture<'_, PlusResult<bool>> {
        self.mapper.delete_by_id(id)
    }
    fn save_batch(&self, entities: Vec<T>) -> BoxFuture<'_, PlusResult<Vec<T>>> {
        self.mapper.insert_batch(entities)
    }
}

/// Fixed interceptor phases; discriminants define execution order.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum InterceptorStage {
    SqlRewrite = 1,
    ParameterTransform = 2,
    Execute = 3,
    ResultVerify = 4,
    ResultTransform = 5,
    Observe = 6,
}

#[derive(Debug, Clone, PartialEq)]
pub struct SqlInvocation {
    pub statement_id: String,
    pub sql: String,
    pub parameters: Vec<Value>,
    pub result: Option<Value>,
    pub attributes: BTreeMap<String, Value>,
}

impl SqlInvocation {
    pub fn new(
        statement_id: impl Into<String>,
        sql: impl Into<String>,
        parameters: Vec<Value>,
    ) -> Self {
        Self {
            statement_id: statement_id.into(),
            sql: sql.into(),
            parameters,
            result: None,
            attributes: BTreeMap::new(),
        }
    }
}

pub trait SqlInterceptor: Send + Sync {
    fn stage(&self) -> InterceptorStage;
    fn intercept<'a>(&'a self, invocation: &'a mut SqlInvocation) -> BoxFuture<'a, PlusResult<()>>;
}

#[derive(Default)]
pub struct InterceptorChain {
    interceptors: Vec<Arc<dyn SqlInterceptor>>,
}

impl InterceptorChain {
    pub fn new(mut interceptors: Vec<Arc<dyn SqlInterceptor>>) -> Self {
        interceptors.sort_by_key(|item| item.stage());
        Self { interceptors }
    }
    pub fn stages(&self) -> Vec<InterceptorStage> {
        self.interceptors.iter().map(|item| item.stage()).collect()
    }
    pub async fn apply(&self, invocation: &mut SqlInvocation) -> PlusResult<()> {
        for interceptor in &self.interceptors {
            interceptor.intercept(invocation).await?;
        }
        Ok(())
    }

    pub async fn apply_before_execute(&self, invocation: &mut SqlInvocation) -> PlusResult<()> {
        for interceptor in self
            .interceptors
            .iter()
            .filter(|item| item.stage() <= InterceptorStage::Execute)
        {
            interceptor.intercept(invocation).await?;
        }
        Ok(())
    }

    pub async fn apply_after_execute(&self, invocation: &mut SqlInvocation) -> PlusResult<()> {
        for interceptor in self
            .interceptors
            .iter()
            .filter(|item| item.stage() > InterceptorStage::Execute)
        {
            interceptor.intercept(invocation).await?;
        }
        Ok(())
    }
}
