[package]
name = "rbatis-plus-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Core conditions, metadata, mapper traits and toolkit for RBatis-Plus"

[dependencies]
rbatis = { workspace = true }
rbs = { workspace = true }
rbdc = { workspace = true }
serde = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
hex = { workspace = true }
dashmap = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
rusqlite = { version = "0.31", features = ["bundled"] }
