[package]
name = "rbatis-plus-generator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["rbatis", "orm", "mybatis-plus", "code-generator", "database"]
categories = ["database", "development-tools"]
documentation = "https://docs.rs/rbatis-plus-generator"
readme = "../README.md"
publish = ["crates-io"]

[dependencies]
rbatis = { workspace = true }
rbs = { workspace = true }
rbdc = { workspace = true }
rbatis-plus-core = { version = "=0.1.1-alpha.1", path = "../rbatis-plus-core" }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
chrono = { workspace = true }
Inflector = { workspace = true }
async-trait = { workspace = true }
handlebars = "6"
askama = "0.12"
maud = "0.26"
